on: [push]
name: test_action
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/greating/action.yaml
        with:
          who-to-greet: 'Ziba'
