name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  deploy:
    runs-on: ubuntu-latest
    environment: ${{matrix.environments}}
    needs: build-and-push
    strategy:
      matrix:
        environments: ["dev", "int"]
    steps:
      - name: deploying
        run: echo "deploying"

      - name: sleep
        run: sleep 5 

  test:
    runs-on: ubuntu-latest
    environment: "prd"
    needs: deploy
    steps:
    - name: test
      run: echo "testing"


  # Chain the next job to the previous one and make it deploy
  # to different environments with manual approvals
  